# Site settings
title : Falacias Lógicas
url: "http://falaciaslogicas.com"

twitter: FalaciaLogica

author :
  name : Jorge Barata
  url: http://jorgebg.com
  github : jorgebg
  twitter : neuralhacker

collections:
  fallacies:
    output: true
    permalink: /:path/

defaults:
  -
    scope:
      type: "fallacies"
    values:
      layout: "fallacy"
